apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-instance
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/tosin2013/ai-accelerator.git
    targetRevision: main
    path: components/operators/gpu-operator-certified/instance/overlays/default
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-gpu-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
