apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator-certified
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/tosin2013/ai-accelerator.git
    targetRevision: main
    path: components/operators/gpu-operator-certified/operator/overlays/stable
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
