apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfd-instance
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/tosin2013/ai-accelerator.git
    targetRevision: main
    path: components/operators/nfd/instance/overlays/default
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-nfd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
